src/ReverseDiffPrototype.jl
test/runtests.jl

This will allow mapping a univariate function over an array to be treated/optimized as a single node operation.

support for map operations

---

src/ReverseDiffPrototype.jl
test/rosenbrock.jl

@mlubin So is this what you meant by generating a graph instead of storing a tape? GC time is now a huge factor, since it becomes the GC's job to free the nodes after back-propagation happens.
Using my usual microbenchmark: 
```julia
using ReverseDiffPrototype
function rosenbrock(x)
a = one(eltype(x))
b = 100 * a
result = zero(eltype(x))
for i in 1:length(x)-1
result += (a - x[i])^2 + b*(x[i+1] - x[i]^2)^2
end
return result
end
x = rand(100000);
out = zeros(x);
g! = ReverseDiffPrototype.gradient(rosenbrock, Input{Float64,100000});
```
On master:
```julia
julia> @time g!(out, x);
3.108355 seconds (4.50 M allocations: 120.544 MB, 7.68% gc time)
```
With this PR:
```julia
julia> @time g!(out, x);
0.267648 seconds (3.40 M allocations: 103.759 MB, 53.69% gc time)
```
The target function's …

store pointer to parent in TapeNodes instead of pushing to a tape stack

---

.travis.yml
src/ReverseDiffPrototype.jl
test/rosenbrock.jl
test/runtests.jl

This makes the API more flexible (no need to specify input type/dimension), and avoids a class of eval-related bugs I found (i.e. nothing works until you get back to top-level, method overwriting improperly initialized the tape head, etc.). 
Additionally, I rewrote `map` to use fewer temporaries, and hardcoded the two-arg and three-arg ForwardDiff fallback `backprop_rule!` definitions to avoid temporary vectors (the generic gradient fallback still allocates a `Vector` and reverts to splatting).
I also realized a conversion-related bug that I'll file an issue for, but is outside the scope of this PR.
EDIT: This PR also enables Travis.

Use generated function instead of `eval` for registering types to tape heads

---

src/ReverseDiffPrototype.jl
test/matrixfun.jl

I decided to do some timing of my original objective function involving some matrix ops for comparison. By adding some specific rules for handling `*`, I got a 50x speedup over master, which is not entirely surprising. It does suggest, though, that we might want to be sure that approaches like #10 allow for these same kinds of optimizations. My intuition, again, is that unlike in JuMP, a lot of the applications ML people have in mind consist of pretty small graphs with "fat" nodes.
Timing:
(master, without matrix ops)
```
0.179432 seconds (6.17 M allocations: 188.689 MB)
20100-element Array{Float64,1}
```
this branch:
```
0.003167 seconds (80.46 k allocations: 3.448 MB)
20100-element Array{Float64,1}
```

add optimizations of matrix ops

---

benchmark/benchmark.jl
benchmark/old_matrix_test.jl
src/ReverseDiffPrototype.jl
src/TraceReal.jl
src/api.jl
src/array.jl
src/trace.jl
test/ArrayTests.jl
test/MiscTests.jl

I had already prepared the jacobian stuff when I found the bug from #16, so I just rolled the proposed macro into this PR.
~~I settled on `@diffpure` as the macro name, since it's a differentiation optimization for pure functions.~~ Changed it to `@fastdiff`, inspired by the existing `@fastmath` in Base. It also means we can use it for other optimizations in the future, since we're not tying it to purity-based optimizations. Feel free to bikeshed the name.

add jacobian methods and fix #16

---

src/derivatives/elementwise.jl

fixes #34 
Test function added [here](https://github.com/JuliaDiff/DiffBase.jl/commit/e33e52ece59c373a0fadde7f7976d0227b3f1f62).

use istracked instead of pure type checking to decide whether to update partials cache for pow/div broadcast methods

---

benchmark/benchmark.jl
docs/src/api.md
examples/gradient.jl
examples/jacobian.jl
src/api/gradients.jl
src/api/hessians.jl
src/api/jacobians.jl
src/api/tape.jl
src/tape.jl
test/api/GradientTests.jl
test/api/HessianTests.jl
test/api/JacobianTests.jl

This removes `compiled_*(...)` methods in favor of just `compile(*Tape(...))`, and refactors `compile` to separate out the generated code from the tape memory. This enables advanced users to use ReverseDiff in a thread-safe way without generating new functions for each thread.

More thread-friendly compilation API method

---

src/api/utils.jl
test/utils.jl

This fixes #59. Test is added [here](https://github.com/JuliaDiff/DiffBase.jl/pull/3). We'll have to re-run Travis once that's merged and tagged to get representative testing in this PR.
Funnily, enough, this also reveals similar bugs in both ForwardDiff and Calculus - both of them appear to get the wrong answer for the Jacobian of the identity. I've checked locally that this PR enables ReverseDiff to get the correct answer, but once the DiffBase PR is merged, tests will fail here, since ReverseDiff is checking against ForwardDiff, which checks against Calculus.
I'll start working on bug fixes for those packages as well.

correct the seeding order for seeded_reverse_pass! functions

---

.travis.yml
REQUIRE
src/ReverseDiff.jl
src/api/tape.jl
test/api/GradientTests.jl
test/api/HessianTests.jl
test/api/JacobianTests.jl

Since this seems like it might not be a terrible idea, I'm opening a PR to figure out whether this is a good change.
As discussed in #70, using `eval()` to generate the forward and reverse pass methods inside `compile()` creates world age issues, which ultimately means that a tape cannot be compiled and used in the same runtime context. This PR fixes that problem by removing the `eval()`ed methods entirely. Instead, to avoid type instability, the compiled tape is augmented with two vectors of concretely typed FunctionWrappers. Each wrapper is built around a functor which, when called, invokes its corresponding instruction's `forward_exec!` or `reverse_exec!` method. 
Performance seems to be ~15% slower on my machine using this branch vs `master` for the rosenbrock example from #70. …

WIP: replace eval()-ed methods with FunctionWrappers.jl

---

.travis.yml
REQUIRE
src/api/hessians.jl
src/api/utils.jl
src/tracked.jl

Fixes #82. The former "correct" behavior was actually dependent on a type inference bug, which got fixed in the final Julia v0.6.0 release.
Test added in https://github.com/JuliaDiff/DiffBase.jl/pull/12, so I'm going to wait to merge this until that gets tagged (so I can re-run Travis here with the test).
cc @NHDaly
EDIT: Also made nightly failures allowable, since the plan is to replace this package by the v0.7 release anyway

fix overly-inclusive convert method at supertype boundary

---

.travis.yml
README.md
REQUIRE
src/ReverseDiff.jl
src/api/Config.jl
src/api/tape.jl
src/api/utils.jl
src/derivatives/elementwise.jl
src/derivatives/linalg/arithmetic.jl
src/derivatives/linalg/reductions.jl
src/derivatives/linalg/special.jl
src/derivatives/propagation.jl
src/derivatives/scalars.jl
src/macros.jl
src/tracked.jl
test/MacrosTests.jl
test/TapeTests.jl
test/TrackedTests.jl
test/api/ConfigTests.jl
test/api/GradientTests.jl
test/api/HessianTests.jl
test/api/JacobianTests.jl
test/derivatives/ElementwiseTests.jl
test/derivatives/LinAlgTests.jl
test/derivatives/ScalarTests.jl
test/runtests.jl
test/utils.jl

Let's see what CI thinks of this. Tests pass locally with no depwarns AFAICT.
The hardest part was updating the `A_mul_B`-style functions to the equivalents using `Adjoint` and `Transpose`; I kinda followed the quickest path to getting things working and the result is pretty messy. The painful number of method overloads there makes me really happy that Cassette exists now and that future AD implementations won't need to struggle through this... 😛 
I didn't end up actually updating to the new broadcast machinery. Doing so would be the Right Thing To Do™️, but tests seem to pass without it. We can put in the work to update to the new broadcast machinery later if the current set of (previously kosher, now hacky) broadcast overloads ends up causing any practical issues.
Assuming CI passes, …

deprecation fixes for Julia v0.7

---

src/tracked.jl

Fixes generic codes like
```julia
using OrdinaryDiffEq, ForwardDiff, ReverseDiff, ParameterizedFunctions
df = @ode_def begin
dx = a*x - b*x*y
dy = -c*y + x*y
end a b c
u0 = [1.,1.]; tspan = (0., 10.); p = [1.5,1.0,3.0];
function auto_sen_l2(f, init, tspan, p, t, alg=Vern6(); diffalg=ForwardDiff.gradient)
test_f(p) = begin
prob = ODEProblem(f,eltype(p).(init),eltype(p).(tspan),p)
sol = solve(prob,alg,abstol=1e-5,reltol=1e-7,saveat=t)
sum(sol.u) do x
sum(z->(1-z)^2/2, x)
end
end
diffalg(test_f, p)
end
t = 0:0.5:10
auto_sen_l2(df, u0, tspan, p, t; diffalg=ReverseDiff.gradient)
```
which rely on `T(x) == convert(T,x)` for `Number` types.

Add constructor <--> convert pun for TrackedReal

---

src/ReverseDiff.jl
src/derivatives/arrays.jl
src/derivatives/linalg/arithmetic.jl
src/tracked.jl
test/derivatives/ArrayFunctionTests.jl
test/runtests.jl

This PR defines a few custom adjoints for some array functions. Currently, it gives a precompilation error in Julia 1.3 and a StackOverFlow in Julia 1.4 for what seems like a Julia bug triggered by https://github.com/JuliaDiff/ReverseDiff.jl/blob/mt/array_funcs/src/derivatives/arrays.jl#L40 and the next block. Commenting these 2 blocks, loading ReverseDiff and then calling:
```julia
using ReverseDiff: TrackedVecOrMat, track
Base.vcat(x::TrackedVecOrMat{T}, xs::AbstractVecOrMat{T}...) where T = track(vcat, x, xs...)
```
triggers the StackOverFlow in Julia 1.4 which again seems like a Julia bug?? I appreciate any help here. This PR is based on #123.

fill, vcat, hcat, cat, reshape, any, and all custom adjoints

---

src/derivatives/linalg/arithmetic.jl
test/derivatives/LinAlgTests.jl

This PR fixes `Adjoint` and `Transpose` support properly without relying on dispatch workarounds. I only had an issue with `transpose` which seems to cause an unusual growth in the tape size when called. I traced the function calls and it's just calling the parametric constructor so it shouldn't be doing this. This needs  further investigation but is not a show stopper.
Supersedes: #147 
Fixes: https://github.com/SciML/DiffEqSensitivity.jl/issues/330

Fix adjoint and transpose properly

---

src/derivatives/broadcast.jl
src/derivatives/elementwise.jl
test/api/GradientTests.jl

This is my attempt to fix #140. The relevant test is here: https://github.com/JuliaDiff/DiffTests.jl/pull/10 and locally it passes.

simple fix for #140

---

src/derivatives/arrays.jl
test/derivatives/ArrayFunctionTests.jl

This PR fixes `vcat(ReverseDiff.track(1.0))` and the likes and tests them. CC: @ChrisRackauckas

Fix single number (v/h)cat

---

Project.toml
src/derivatives/broadcast.jl
test/compat/CompatTests.jl
test/runtests.jl

This PR fixes compatibility with FillArrays 0.10.

fix FillArrays 0.10 compat

---

src/tracked.jl
test/TrackedTests.jl

The `Base.isapprox` function relies on `Base.rtoldefault` to return an acceptable margin of error for inexact comparisons. If the default implementation for types descending from `AbstractFloat` returns `sqrt(eps(T))`, the one for types descending from `Real` simply returns 0.
As `TrackedReal` descends from `Real` and not `AbstractFloat`, a custom `Base.rtoldefault` implementation returning `sqrt(eps(T))` ensures that `iscompare` behaves correctly for `TrackedReal` approximative comparisons.
Fixes #165

Fix `Base.isapprox` for `TrackedReal`

---

test/utils.jl

https://github.com/JuliaDiff/DiffRules.jl/pull/73 broke the tests since, similar to `polygamma` the current DiffRules integration and test infrastructure can't deal with functions with two arguments of which one has to be an integer.
Ideally, this would be tested properly but this PR is a temporary solution that requires minimal changes and fixes also the downstream tests in DiffRules.
It seems one problem with these functions is that the arguments are promoted when they are forwarded to ForwardDiff since everything is packed in a static vector - in these cases it would be better to not promote and work with the DiffRules definitions directly. I wonder why this is not done already and instead ReverseDiff calls ForwardDiff?

Fix broken tests

---

Project.toml
src/tracked.jl
test/TrackedTests.jl

This PR adds overloads for `fld`, `cld`, and `div`, which all return a `MethodError` on master. The overloads for `div` are the same ones used by ForwardDiff: https://github.com/JuliaDiff/ForwardDiff.jl/blob/29332b12075e66e056843d3b4207d856f98772b3/src/dual.jl#L287-L291

Add overloads for fld, cld, and div

---

Project.toml
src/tracked.jl
test/TrackedTests.jl

This PR fixes `getindex` for non-`Int` indices (fixes #139), removes undesired definitions for `getindex` caused by Varargs, adds `@propagate_inbounds` annotations, and adds tests.

Fix `getindex`

---

Project.toml
src/ReverseDiff.jl
src/derivatives/elementwise.jl
src/derivatives/scalars.jl
test/derivatives/ElementwiseTests.jl
test/derivatives/ScalarTests.jl
test/utils.jl

This PR fixes some problems with the DiffRules integration and its tests. It is needed for https://github.com/JuliaDiff/DiffRules.jl/pull/79 (relevant DiffRules tests pass with that PR).
Mainly, the PR
- disables DiffRules definitions and tests for functions with complex outputs and derivatives as they are not supported by ReverseDiff
- adds support for `NaN` comparisons to the tests (necessary since in DiffRules undefined and non-existing derivatives are implemented as `NaN` and hence otherwise comparisons with ForwardDiff will fail if both return `NaN`)
- changes the tests such that they compare ReverseDiff results with the results of the corresponding ForwardDiff calls (currently, e.g., derivatives wrt to two arguments in ReverseDiff are compared with two separately computed …

Improve DiffRules integration and tests

---

Project.toml
src/derivatives/linalg/arithmetic.jl
test/api/GradientTests.jl
test/derivatives/LinAlgTests.jl

This "fixes" some weird behavior in the multiplication code. It occurred in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8a3027b_vs_960870e/PositiveFactorizations.primary.log PositiveFactorizations.jl. In their case, they want to multiply a matrix by the transpose of a row matrix (i.e., vector-like) into a vector. "By chance", this works out from the pov of dimensions, but from the pov of types having such a `mul!` method is weird and we may not wish to continue to support this (https://github.com/JuliaLang/julia/pull/49521#discussion_r1178114739). To make this package (and PositiveFactorizations.jl) run smoothly across (past and upcoming) versions, I proposed to simply catch that case and reshape the output vector to a matrix. In fact, this may even turn out to …

Handle matrix times matrix = vector case

---

Project.toml
src/macros.jl
test/ChainRulesTests.jl

I noticed that we don't esc the types of the arguments in the `@grad_from_chainrules` macro. This PR fixes that.

Allow custom struct args to grad_from_chainrules macro

---

Project.toml
src/derivatives/linalg/arithmetic.jl
test/derivatives/LinAlgTests.jl

I think this fixes the aforementioned issue. Closes #235

Resolve #235

---

README.md

#246 pointed out that the docs are not correctly deployed. Unfortunately, this is still the case so in the meantime a quick "bandaid" fix which makes the stable docs accessible is just to change the stable docs link.
Right now the stable docs are hard to find unless you know that removing `/stable` from the url goes there.
Apologies if this is the wrong fix to the problem, it was just bugging me.

(Temporarily) fix stable docs link in README.md

---

.github/workflows/TagBot.yml

@gdalle #253 didn't fix the stable docs build. https://github.com/JuliaDiff/ReverseDiff.jl/actions shows that the TagBot action executed successfully but did not trigger a docs build. I assume the remaining issue might be an outdated TagBot config. In this PR I copied the recommended TagBot config.

Update TagBot config

---

Project.toml
src/ReverseDiff.jl
test/TrackedTests.jl

Should fix https://github.com/JuliaDiff/ReverseDiff.jl/issues/100. 
Similar to this PR for ForwardDiff: https://github.com/JuliaDiff/ForwardDiff.jl/pull/687

Add AbstractIrrational to list of types for TrackedReal promote_rule definitions

---

Project.toml
src/ReverseDiff.jl

It is a Base function that returns a scalar.
https://github.com/SciML/DiffEqBase.jl/blame/master/src/internal_itp.jl#L46
https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/14272335727/job/40008186966?pr=2662#step:6:1251
@oscardssmith

Skip the exponent function
